namespace WinterRose.WinterForgeSerializing.Formatting.HumanReadable.Parsing;

internal enum HumanReadableTokenKind
{
    Identifier,
    Number,
    String,
    Comment,
    Directive,
    NewLine,
    EndOfFile,

    KeywordReturn,
    KeywordAlias,
    KeywordAs,
    KeywordInherits,
    KeywordAnonymous,
    KeywordImport,
    KeywordIf,
    KeywordElse,
    KeywordWhile,
    KeywordFor,
    KeywordContainer,
    KeywordTemplate,
    KeywordVariables,
    KeywordThis,
    KeywordTrue,
    KeywordFalse,
    KeywordNull,
    KeywordDefault,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Pipe,
    Ampersand,
    Bang,
    Equals,
    DoubleEquals,
    NotEquals,
    GreaterThan,
    GreaterOrEqual,
    LessThan,
    LessOrEqual,
    AndAnd,
    OrOr,
    Arrow,
    FatArrow,

    Dot,
    Comma,
    Semicolon,
    Colon,

    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket
}
